image: docker:stable


variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  ZYRE_CPP_IMAGE: git.ropod.org:4567/ropod/docker/ropod-base:zyre-cpp
  KINETIC_BASE_IMAGE: git.ropod.org:4567/ropod/docker/ropod-base:kinetic
  KINETIC_MSGS_IMAGE: git.ropod.org:4567/ropod/docker/ropod-base:kinetic-msgs-python3

services:
  - name: docker:dind
    command: ["--insecure-registry=git.ropod.org:4567"] # self-signed cetificate

stages:
  - build
  - release

before_script:
  - docker info
  - apk add --no-cache py-pip
  - pip install -Iv docker-compose==1.23.2
  - docker-compose -v
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.ropod.org:4567

build:
  stage: build
  script:
    - docker-compose build
    - docker push $ZYRE_CPP_IMAGE
    - docker push $KINETIC_BASE_IMAGE
    - docker push $KINETIC_MSGS_IMAGE
  only:
    - master
