image: docker:stable


variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  ZYRE_CPP_IMAGE: git.ropod.org:4567/ropod/docker/ropod-base:zyre-cpp
  KINETIC_BASE_IMAGE: git.ropod.org:4567/ropod/docker/ropod-base:kinetic
  KINETIC_MSGS_IMAGE: git.ropod.org:4567/ropod/docker/ropod-base:kinetic-msgs-python3
  FMS_BASE_IMAGE: git.ropod.org:4567/ropod/docker/ropod-base:fms
  ROPOD_REGISTRY: git.ropod.org:4567/ropod/
  DOCKERHUB_BASE_IMAGE: ropod/ropod-base:fms
  DOCKER_HUB_ORG: ropod

services:
  - name: docker:dind
    command: ["--insecure-registry=git.ropod.org:4567"] # self-signed cetificate

stages:
  - build
  - release

before_script:
  - docker info
  - apk add --no-cache py-pip
  - pip install -Iv docker-compose==1.23.2
  - docker-compose -v
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.ropod.org:4567

zyre base:
  stage: build
  script:
    - docker-compose build zyre-cpp
    - docker push $ZYRE_CPP_IMAGE

ROS kinetic:
  stage: build
  script:
    - docker-compose build ros-base ros-comm
    - docker push $KINETIC_BASE_IMAGE
    - docker push $KINETIC_MSGS_IMAGE

fleet management:
  stage: build
  script:
    - docker-compose build fms-base
    - docker push $FMS_BASE_IMAGE
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - docker tag $FMS_BASE_IMAGE $DOCKERHUB_BASE_IMAGE
    - docker push $DOCKERHUB_BASE_IMAGE
