version: "2"
services:
  zyre-cpp:
    image: git.ropod.org:4567/ropod/docker-base-images/ropod-base:cpp
    build:
      context: ./zyre/cpp/
      dockerfile: Dockerfile
    build:
      context: .
  ros:
    image: git.ropod.org:4567/ropod/docker-base-images/ropod-base:ros-kinetic
    build:
      context: .
      dockerfile: ropod-base-kinetic/Dockerfile
